<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/
function selector_scripts() {

wp_register_script( 'sly', get_stylesheet_directory_uri().'/js/sly.min.js', array('jquery-core'), true);
wp_register_script('selector', get_stylesheet_directory_uri() . '/js/selector.js', array('jquery-core','sly'), true);
wp_enqueue_script( 'sly' );
wp_enqueue_script( 'selector' );

}
add_action( 'wp_enqueue_scripts', 'selector_scripts' );

/*______________________________________________________________________
				Experiment with re-adding quantity buttons
________________________________________________________________________*/
wp_register_script('qty_btns', get_stylesheet_directory_uri() . '/js/qty_btns.js', array('jquery-core'), true);
wp_enqueue_script( 'qty_btns' );
